# Generated by Django 2.2.1 on 2019-05-04 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(help_text='Enter Post Title', max_length=20)),
                ('content', models.TextField(help_text='Post Content')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 5, 4, 15, 36, 59, 659016))),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
    ]
