# Generated by Django 2.1.7 on 2019-04-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leblog', '0002_auto_20190404_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
