# Generated by Django 2.1.7 on 2019-05-03 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leblog', '0003_auto_20190404_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 5, 3, 0, 7, 46, 750831)),
        ),
    ]
