# Generated by Django 2.1.7 on 2019-05-03 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leblog', '0004_auto_20190503_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 5, 3, 0, 8, 58, 340015)),
        ),
    ]
