# Generated by Django 2.1.7 on 2019-05-03 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leblog', '0005_auto_20190503_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 5, 3, 0, 9, 32, 505389)),
        ),
    ]
