# Generated by Django 2.1.7 on 2019-05-04 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leblog', '0008_auto_20190503_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(help_text='Link to Image', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 5, 3, 22, 35, 24, 560751)),
        ),
    ]
